language: objective-c
 
before_install:
 - export LANG=en_US.UTF-8
 - gem install cocoapods -r
 - pod setup
 - sudo easy_install cpp-coveralls
   
script:
    - xctool -workspace RACSample.xcworkspace -scheme RACSample -sdk iphonesimulator build test  GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - ./script/coveralls.sh -r ./ -e Pods -e Tests
