language: objective-c
 
before_install:
 - export LANG=en_US.UTF-8
 - gem install cocoapods -r
 - pod setup
 
script:
    - xctool -workspace RACSample.xcworkspace -scheme RACSample -sdk iphonesimulator build test \
      TEST_AFTER_BUILD=YES \
      TEST_HOST= \
      GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
      GCC_GENERATE_TEST_COVERAGE_FILES=YES

send-coverage:
  coveralls -e RACSampleTests      

after_success:
  - make send-coverage
